# Generated by Django 4.0.2 on 2022-04-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_node_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='DateTime',
            field=models.CharField(max_length=200),
        ),
    ]
