# Generated by Django 4.0.4 on 2022-06-04 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ErrorId', models.IntegerField(blank=True, null=True)),
                ('MacAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('SetPointTemperature', models.FloatField(blank=True, null=True)),
                ('ControlStatus', models.BooleanField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Value', models.BooleanField()),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('Action', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('Presence', models.BooleanField(blank=True, null=True)),
                ('ErrorId', models.IntegerField(blank=True, null=True)),
                ('FanCoilTemperature', models.FloatField(blank=True, null=True)),
                ('HomeTemperature', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('Node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.node')),
            ],
        ),
        migrations.CreateModel(
            name='Neighbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RSSI', models.FloatField(blank=True, null=True)),
                ('Node1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Neighbor1', to='account.node')),
                ('Node2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.node')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateTimeField(blank=True, null=True)),
                ('NodeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.node')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
