# Generated by Django 4.0.4 on 2022-06-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_node_security_securitystation_usernode_nodestation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodestation',
            name='SetPointTemperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodestation',
            name='faucetState',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
