# Generated by Django 4.0.2 on 2022-06-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_nodestation_setpointtemperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodestation',
            name='DateTime',
            field=models.DateTimeField(),
        ),
    ]
