# Generated by Django 4.0.2 on 2022-06-30 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_nodestation_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanCoil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valv', models.BooleanField(blank=True, null=True)),
                ('valvstate', models.BooleanField(blank=True, null=True)),
                ('Temperature', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='node',
            old_name='ControlStatus',
            new_name='permissions',
        ),
        migrations.AddField(
            model_name='node',
            name='mode',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='FanCoilStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valv', models.BooleanField(blank=True, null=True)),
                ('valvstate', models.BooleanField(blank=True, null=True)),
                ('Temperature', models.FloatField(blank=True, null=True)),
                ('FanCoilId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.fancoil')),
            ],
        ),
        migrations.AddField(
            model_name='fancoil',
            name='Node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.node'),
        ),
    ]
